title: Hola
author: Diya Chengappa
email: dchengappa@ebnet.org
description: > # this means to ignore newlines until "baseurl:"

# social links
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
instagram_username: diya_chengappa3

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
